##发布环境设置
server:
  #tomcat端口  比如http://{ip}:{port}{/context-path}中的{port} 纯数字
  port: 18080
common:
  datasource:
    #postgresql url连接信息
    url: jdbc:postgresql://localhost:5432/youyaboot
    #数据库用户名
    username: postgres
    #数据库密码
    password: password
    #mysql8新驱动名称
    driverClassName: org.postgresql.Driver

spring:
  redis:
    #redis ip
    host: bijiben
    #redis 端口
    port: 6379
    #不允许redis密码为空字符串 可以不设置 password:后面不跟任何内容和空格
    password:
    #redis 单机环境下连接池信息
    pool:
      max-active: 8
      max-idle: 10
      min-idle: 0
      max-wait: -1
    timeout: 0
    #所有的redis 缓存都会加入下面的前缀 方便管理
    keyPrefix: youyaboot-admin.
#druid管理后台 http://localhost:18080/youyaboot-admin/druid/ 可以查看数据源的状态 账号/密码：admin/123456
  monitor:
    druid:
      userName: admin
      password: 123456
      allowIps: 127.0.0.1
      denyIps: 10.1.1.1
      filters: stat,log4j
  devtools:
      restart:
      #是否开启热部署 另外需要配置ide的配置一同生效
          enabled: false

magicalcoder:
  file:
    upload:
        #由于spring boot是jar方式执行，无法自动映射上传文件访问地址，采取单独映射方法
        mapping:
          #文件要上传到的硬盘路径 例如 windows: /E:/tmp/test/  linux: /home/web/file/upload/ 如果不设置 则会自动查找classpath路径下的upload
          uploadDiskFolder:
          #虚拟访问映射地址 请尽量不要改动 AdminCommonFileRestController里面有根据这个返回给前端 /.*/格式 最后1个/别忘记了
          requestPrefix: /upload/
  #超级管理员账号名称 密码默认：magicalcoder
  superUserName: magicalcoder
